name           = ""

bg             = ""
fg             = ""

black          = ""
red            = ""
green          = ""
yellow         = ""
blue           = ""
magenta        = ""
cyan           = ""
white          = ""

bgDim          = ""
bg0            = ""
bg1            = ""
bg2            = ""
bg3            = ""
bg4            = ""
bg5            = ""
bg6            = ""
bg7            = ""
bg8            = ""

fgDim          = ""
fgBright       = ""

whiteDim       = ""
redDim         = ""
greenDim       = ""
yellowDim      = ""
blueDim        = ""
magentaDim     = ""
cyanDim        = ""
blackDim       = ""

blackBright    = ""
redBright      = ""
greenBright    = ""
yellowBright   = ""
blueBright     = ""
magentaBright  = ""
cyanBright     = ""
whiteBright    = ""