#!/usr/bin/env zsh
# this function updates plugins to the latest version
# if the first argument is a plugin or framework name, only that plugin or framework is updated
function zert-update(){
    declare -A PLUGINS
    if [ "$#" -gt 0 ]; then # if user provided a name
	# find the hash for this name from zert.lock
	local PLUGIN_DATA="$(grep "$1" "$ZERT_LOCK_FILE" | cut -d';' -f2-)"
	if [ ! -n "$PLUGIN_DATA" ]; then
	    echo "no data is available for a plugin named '$1'" >&2
	    return 1
	fi
	PLUGINS[$1]="$PLUGIN_DATA"
    else
	# get a list of all the plugins from zert.lock
	while read -r LINE; do
	    PLUGINS[$(echo $LINE | cut -d';' -f1)]="$(echo $LINE | cut -d';' -f2-)"
	done < "$ZERT_LOCK_FILE"
	unset LINE
    fi
    for NAME PLUGIN_DATA in ${(kv)PLUGINS}; do
       	local HASH="$(echo $PLUGIN_DATA | cut -d';' -f1)"
	local TYPE="$(echo $PLUGIN_DATA | cut -d';' -f2)"
       	local URL="$(echo $PLUGIN_DATA | cut -d';' -f3)"
        if [[ "$TYPE" == "url" ]]; then # plugin is single file loaded with a url
	    rm "$ZERT_DATA_HOME/plugins/$NAME.plugin.zsh"
	    sed -i "/$NAME;$HASH;$TYPE;$URL/d" "$ZERT_LOCK_FILE"
	    printf "updating '$NAME'..."
	    zert-load-url "$PLUGIN_URL" --name "$NAME"
	    echo "done"
	elif [[ "$TYPE" == "git" ]]; then # plugin is a git repo
	    printf "updating '$NAME'..."
	    local GIT_DIR="$ZERT_DATA_HOME/plugins/$NAME/.git"
	    git --dir-dir="$GIT_DIR" switch - &> /dev/null || true
	    git --git-dir="$GIT_DIR" pull --all &> /dev/null || true
	    local NEW_HEAD="$(git --git-dir="$GIT_DIR" rev-parse HEAD)"
	    sed -i "s/$NAME;$HASH/$NAME;$NEW_HEAD/" "$ZERT_LOCK_FILE"
	    echo "done"
	else # plugin is not installed
	    printf "installing '$NAME' latest version..."
	    sed -i "/$NAME/d" "$ZERT_LOCK_FILE"
	    if [[ "$TYPE" == "git" ]]; then zert-load-git "$URL" --name "$NAME"
	    elif [[ "$TYPE" == "framework" ]]; then zert-utilize "$NAME" --url "$URL"
            else zert-load-url "$URL" --name "$NAME"
	    fi
	    echo "done"
	fi
    done
    echo "reload your shell"
    unset PAIR PLUGINS
}
