#!/usr/bin/env zsh
# parses arguments for zert load functions
function zert-parse_args(){
    while [ "$#" -gt 0 ]; do
	case "$1" in
	    -n|--name)
		export PLUGIN_NAME="$2"
		shift 2
		;;
	    -i|--ignore-alias)
		export IGNORE_ALIAS=1
		shift
		;;
	    *)
		echo "unknown argument '$1'" >&2
		return 1
		;;
	esac
    done
}
