(provide 'modus-custom)
(require 'modus-colors)
;; this is my custom theme using the modus-themes package as a framework for coloring emacs
;; the value for the colors are provided by my custom script `pelz` and are automatically generated in the
;; 'modus-colors.el' file
(custom-set-variables '(modus-themes-common-palette-overrides
      ;; syntax highlighting
      '((keyword red)
        (string green)
        (fringe bg)
        (cursor fg-main)
        (type yellow)
        (preprocessor magenta)
        (variable fg-main)
        (fnname cyan)
        (builtin magenta)
        (docstring green-faint)
        (docmarkup green)
        (warning rust)
      ;; line number column
        (fg-line-number-inactive fg-dim)
        (fg-line-number-active fg-mode-line-inactive)
        (bg-line-number-inactive bg-main)
        (bg-line-number-active bg-hl-line)
      ;; inline diagnostics (undercurls)
        (underline-err red-faint)
        (underline-warning yellow-faint)
        (underline-note cyan-faint)

      ;; highlighting matched parenthesis pairs
        (bg-paren-match bg-yellow-nuanced)
        (fg-paren-match fg-main)
        (bg-paren-expression bg-yellow-nuanced)
        (underline-paren-match unspecified)
        (bg-prominent-err bg-red-intense)
        (fg-prominent-err fg-main)
      ;; UI elements
        (keybind blue)
      ;; completions
        (fg-completion-match-0 red)
        (fg-completion-match-1 green-intense)
        (fg-completion-match-2 gold)
        (fg-completion-match-3 blue)
        (bg-completion-match-0 unspecified)
        (bg-completion-match-1 unspecified)
        (bg-completion-match-2 unspecified)
        (bg-completion-match-3 unspecified)
      ;; search
        (bg-search-current bg-ochre)
        (bg-search-lazy bg-yellow-nuanced)
        (bg-search-replace bg-blue-subtle)
        (bg-search-rx-group-0 bg-blue-intense)
        (bg-search-rx-group-1 bg-green-intense)
        (bg-search-rx-group-2 bg-red-intense)
        (bg-search-rx-group-3 bg-magenta-intense)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(name magenta)
(identifier yellow-faint)
(err red)
(info cyan-cooler)

(bg-prominent-warning bg-yellow-intense)
(fg-prominent-warning fg-main)
(bg-prominent-note bg-cyan-intense)
(fg-prominent-note fg-main)
(bg-active-argument bg-yellow-nuanced)
(fg-active-argument yellow-cooler)
(bg-active-value bg-cyan-nuanced)
(fg-active-value cyan-cooler)
(constant blue-cooler)
(rx-construct green-cooler)
(rx-backslash magenta)
(accent-0 blue-cooler)
(accent-1 magenta-warmer)
(accent-2 cyan-cooler)
(accent-3 yellow)
(fg-button-active fg-main)
(fg-button-inactive fg-dim)
(bg-button-active bg-active)
(bg-button-inactive bg-dim)
(date-common cyan)
(date-deadline red)
(date-event fg-alt)
(date-holiday red-cooler)
(date-holiday-other blue)
(date-now fg-main)
(date-range fg-alt)
(date-scheduled yellow-warmer)
(date-weekday cyan)
(date-weekend red-faint)
(fg-link blue-warmer)
(bg-link unspecified)
(underline-link blue-warmer)
(fg-link-symbolic cyan)
(bg-link-symbolic unspecified)
(underline-link-symbolic cyan)
(fg-link-visited magenta)
(bg-link-visited unspecified)
(underline-link-visited magenta)
(mail-cite-0 blue-warmer)
(mail-cite-1 yellow-cooler)
(mail-cite-2 cyan-cooler)
(mail-cite-3 red-cooler)
(mail-part blue)
(mail-recipient magenta-cooler)
(mail-subject magenta-warmer)
(mail-other magenta-faint)
(bg-mark-delete bg-red-subtle)
(fg-mark-delete red-cooler)
(bg-mark-select bg-cyan-subtle)
(fg-mark-select cyan)
(bg-mark-other bg-yellow-subtle)
(fg-mark-other yellow)
(fg-prompt cyan-cooler)
(bg-prompt unspecified)
(bg-prose-block-delimiter bg-dim)
(fg-prose-block-delimiter fg-dim)
(bg-prose-block-contents bg-dim)
(bg-prose-code unspecified)
(fg-prose-code cyan-cooler)
(bg-prose-macro unspecified)
(fg-prose-macro magenta-cooler)
(bg-prose-verbatim unspecified)
(fg-prose-verbatim magenta-warmer)
(prose-done green)
(prose-todo red)
(prose-metadata fg-dim)
(prose-metadata-value fg-alt)
(prose-table fg-alt)
(prose-table-formula magenta-warmer)
(prose-tag magenta-faint)
(rainbow-0 fg-main)
(rainbow-1 magenta-intense)
(rainbow-2 cyan-intense)
(rainbow-3 red-warmer)
(rainbow-4 yellow-intense)
(rainbow-5 magenta-cooler)
(rainbow-6 green-intense)
(rainbow-7 blue-warmer)
(rainbow-8 magenta-warmer)
(bg-space unspecified)
(fg-space border)
(bg-space-err bg-red-intense)
(bg-term-black "#000000")
(fg-term-black "#000000")
(bg-term-black-bright "#595959")
(fg-term-black-bright "#595959")
(bg-term-red red)
(fg-term-red red)
(bg-term-red-bright red-warmer)
(fg-term-red-bright red-warmer)
(bg-term-green green)
(fg-term-green green)
(bg-term-green-bright green-cooler)
(fg-term-green-bright green-cooler)
(bg-term-yellow yellow)
(fg-term-yellow yellow)
(bg-term-yellow-bright yellow-warmer)
(fg-term-yellow-bright yellow-warmer)
(bg-term-blue blue)
(fg-term-blue blue)
(bg-term-blue-bright blue-warmer)
(fg-term-blue-bright blue-warmer)
(bg-term-magenta magenta)
(fg-term-magenta magenta)
(bg-term-magenta-bright magenta-cooler)
(fg-term-magenta-bright magenta-cooler)
(bg-term-cyan cyan)
(fg-term-cyan cyan)
(bg-term-cyan-bright cyan-cooler)
(fg-term-cyan-bright cyan-cooler)
(bg-term-white "#a6a6a6")
(fg-term-white "#a6a6a6")
(bg-term-white-bright "#ffffff")
(fg-term-white-bright "#ffffff")
(fg-heading-0 cyan-cooler)
(fg-heading-1 fg-main)
(fg-heading-2 yellow-faint)
(fg-heading-3 blue-faint)
(fg-heading-4 magenta)
(fg-heading-5 green-faint)
(fg-heading-6 red-faint)
(fg-heading-7 cyan-faint)
(fg-heading-8 fg-dim)
(bg-heading-0 unspecified)
(bg-heading-1 unspecified)
(bg-heading-2 unspecified)
(bg-heading-3 unspecified)
(bg-heading-4 unspecified)
(bg-heading-5 unspecified)
(bg-heading-6 unspecified)
(bg-heading-7 unspecified)
(bg-heading-8 unspecified)
(overline-heading-0 unspecified)
(overline-heading-1 unspecified)
(overline-heading-2 unspecified)
(overline-heading-3 unspecified)
(overline-heading-4 unspecified)
(overline-heading-5 unspecified)
(overline-heading-6 unspecified)
(overline-heading-7 unspecified)
(overline-heading-8 unspecified))
      t))

(defun oxcl/modus-themes-apply-custom-faces ()
  (modus-themes-with-colors
    (custom-set-faces
     ;; tree-sitter font lock faces
     `(font-lock-operator-face      ((,c :foreground ,rust)))
     `(font-lock-number-face        ((,c :foreground ,magenta)))
     `(font-lock-constant-face      ((,c :foreground ,magenta)))
     `(font-lock-builtin-face       ((,c :weight normal)))
     `(font-lock-punctuation-face   ((,c :foreground ,yellow-intense)))
     `(font-lock-type-face          ((,c :weight normal)))
     `(font-lock-function-call-face ((,c :foreground ,cyan)))
     `(font-lock-property-name-face ((,c :foreground ,blue)))
     `(font-lock-warning-face       ((,c :weight normal)))
     ;; add extra padding to mode line
     `(mode-line                    ((,c :box (:line-width (4 . 4) :color ,bg-mode-line-active)
                                         :underline (:color ,border-mode-line-active :position t)
                                         :overline ,border-mode-line-active)))
     `(mode-line-inactive           ((,c :box (:line-width (4 . 4) :color ,bg-mode-line-inactive)
                                         :underline (:color ,border-mode-line-inactive :position t)
                                         :overline ,border-mode-line-inactive)))
     ;; modification to other faces
     `(idle-highlight               ((,c (:background ,bg-active))))
     `(jinx-misspelled              ((,c (:underline (:style wave :color ,green-faint)))))
     `(show-paren-match             ((,c :weight bold)))
     `(show-paren-mismatch          ((,c :weight bold)))
     ;; dashboard
     `(dashboard-items-face         ((,c :box (:line-width 3 :color ,bg-main))))
     `(dashboard-heading            ((,c :expand t :box (:line-width 7 :color ,bg-main)
                                         :underline (:position 5))))
     ;; volatile-highlights
     `(secondary-selection           ((,c :foreground unspecified :background ,bg-red-subtle))))))

     ;; tabs
;;     `(tab-line                     ((,c :height 1.0
;;                                         :foreground ,fg-dim
;;                                         :box (:line-width (-1 . 3) :color ,bg-tab-bar)
;;                                         :overline ,bg-active
;;                                         :underline (:color ,border :position t))))
;;     `(tab-line-tab-current          ((,c :foreground ,fg-mode-line-active
;;                                          :box nil
;;                                         :underline (:color ,cyan :position t))))
;;     `(tab-line-tab-inactive         ((,c :box nil
;;                                          :slant normal :foreground ,fg-mode-line-inactive)))
;;     `(tab-line-tab-special          ((,c :slant oblique))))))
(add-hook 'modus-themes-after-load-theme-hook #'oxcl/modus-themes-apply-custom-faces)
