experimental-features = nix-command flakes
substituters = https://cache.nixos.org https://cache.nixos.org/ https://helium-dev.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= helium-dev.cachix.org-1:dpzYcGK9ck6V16XyiAClKHpdSUrz6U9uvEWgUP9FMYg=
