#!/usr/bin/env zsh
# downloads single file plugin from url if doesn't exist and loads it
function zert-load-url(){
    # parse inputs
    local PLUGIN_URL="$1"
    if [[ ! -n "$PLUGIN_URL" ]]; then
	echo "argument for zert-load-url is missing" >&2
	return 1
    fi
    local PLUGIN_FILE="$(basename $PLUGIN_URL)"
    shift
    zert-parse-args "$@" # parsest optional input parameters that are common among load functions
    if [[ ! -n "$PLUGIN_NAME" ]]; then
	local PLUGIN_NAME="${PLUGIN_FILE%%.*}"
    fi
    local PLUGIN_PATH="$ZERT_DATA_HOME/plugins/$PLUGIN_NAME.plugin.zsh"

    # ensure plugin is available
    if [[ ! -f "$PLUGIN_PATH" ]]; then # plugin should be downloaded
	local TEMP_FILE="$(mktemp)"
	echo "[zert] downloadig '$PLUGIN_NAME' from '$PLUGIN_URL'..."
	if ! curl -s "$PLUGIN_URL" -o "$TEMP_FILE"; then
	    echo "there was an error downloading $PLUGIN_NAME from $PLUGIN_URL" >&2
	    rm -f "$TEMP_FILE"
	    return 1
	fi
	# check hash for plugin
	local HASH="$(md5sum "$TEMP_FILE" | cut -d' ' -f1)"
	local HASH_QUERY_RESULT="$(grep "$PLUGIN_NAME" "$ZERT_LOCK_FILE")"
	if [[ ! -n "$HASH_QUERY_RESULT" ]]; then
            # add plugin hash to zert.lock if doesn't exist
	    echo "$PLUGIN_NAME;$HASH;url;$PLUGIN_URL" >> "$ZERT_LOCK_FILE"
	elif [[ "$(echo $HASH_QUERY_RESULT | cut -d';' -f-2)" != "$PLUGIN_NAME;$HASH" ]] ; then 
            # plugin exists in zert.lock but with a different hash print error and return
	    echo "! the plugin $PLUGIN_NAME has a different hash from the one mentioned in $ZERT_LOCK_FILE" >&2
	    echo "! this usually happens when the file has changed or the url for the plugin has become broken" >&2
	    echo "! firt ten lines of the downloaded file is as follows:" >&2
	    cat "$TEMP_FILE" | head -n10 >&2
	    echo "! expected hash: $(echo $HASH_QUERY_RESULT | cut -d'=' -f2)" >&2
	    echo "! but received : $HASH" >&2
	    echo "! remove the line which contains '$PLUGIN_NAME' from $ZERT_LOCK_FILE or do zert-update '$PLUGIN_NAME'" >&2
	    echo "! this usually fixes it." >&2
	    rm -f "$TEMP_FILE"
	    return 1
	fi
	# if hash check was successful move the plugin to its path
	mv "$TEMP_FILE" "$PLUGIN_PATH"
	zcompile -R "$PLUGIN_PATH" > /dev/null 2>&1
    fi
    # if ignore-alias flag is enabled stop plugin aliases from being set
    [[ -n "$IGNORE_ALIAS" ]] && alias(){ :; }
    source "$PLUGIN_PATH" # loading the plugin
    [[ -n "$IGNORE_ALIAS" ]] && unfunction alias
    
    unset PLUGIN_NAME
    unset IGNORE_ALIAS
}
