#!/usr/bin/env zsh
function zert-load-omz(){
    # parse arguments
    local TYPE="$1" # either theme, lib or plugin
    local NAME="$2"
    shift 2
    while [ "$#" -gt 0 ]; do
	case "$1" in
	    -i|--ignore-alias)
		local IGNORE_ALIAS=1
		shift
		;;
	    *)
		echo "unknown argument '$1'" >&2
		return 1
	esac
    done
    if [[ "$TYPE" == "plugin" ]]; then
	local PLUGIN_DIR="$ZERT_DATA_HOME/ohmyzsh/plugins/$NAME"
	if [[ ! -d "$PLUGIN_DIR" ]]; then
	    echo "$NAME plugin not found in ohmyzsh" >&2
	    return 1
	fi
	fpath+=($PLUGIN_DIR)
	[[ -n "$IGNORE_ALIAS" ]] && alias() { :; }
	[[ -f "$PLUGIN_DIR/$NAME.plugin.zsh" ]] && source "$PLUGIN_DIR/$NAME.plugin.zsh"
	[[ -n "$IGNORE_ALIAS" ]] && unfunction alias
        echo "$PLUGIN_DIR" >> "$ZERT_DATA_HOME/omz_plugins"
    elif [[ "$TYPE" == "lib" ]]; then
	source "$ZERT_DATA_HOME/ohmyzsh/lib/$NAME.zsh"
    elif [[ "$TYPE" == "theme" ]]; then
	source "$ZERT_DATA_HOME/ohmyzsh/themes/$NAME.zsh-theme"
    else
	echo "unknown type '$TYPE'" >&2
	return 1
    fi
}
