#!/usr/bin/env bash
# this file is loaded by direnv before loading any .env or .envrc files when cding into directories.


export DIRENV_LOADED=1 # used by my custom zsh-powerlevel10k prompt segment for direnv

NIX_DIRENV_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/nix-direnv"
if [[ ! -d "$NIX_DIRENV_PATH" ]]; then
    echo "downloading nix-direnv. this only happens once"
    git clone "https://github.com/nix-community/nix-direnv" "$NIX_DIRENV_PATH"
fi
source "$NIX_DIRENV_PATH/direnvrc"
