#!/usr/bin/env sh
# make sure .profile is only sourced once for wayland
if [ ! -z $_WAYLAND_PROFILE_SOURCED ]; then return; else export _WAYLAND_PROFILE_SOURCED=1; fi

# general profile which is used for x11 and wayland
source "${XDG_CONFIG_HOME:-$HOME/.config}/profile"
