#!/usr/bin/env bash
# this file is loaded by direnv before loading any .env or .envrc files when cding into directories.


export DIRENV_LOADED=1 # used by my custom zsh-powerlevel10k prompt segment for direnv

# activate nix-direnv (download if not available)
if command -v nix >/dev/null 2>&1 && ! has nix_direnv_version || ! nix_direnv_version 3.0.7; then
    source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.1.2/direnvrc" "sha256-Di03ad3a0ueGi6CGrfhrQzyGdQIg9APXIPCAMNQgWYM="
fi
