#!/usr/bin/env bash
# this file is loaded by direnv before loading any .env or .envrc files when cding into directories.


export DIRENV_LOADED=1 # used by my custom zsh-powerlevel10k prompt segment for direnv

# activate nix-direnv (download if not available)
if ! has nix_direnv_version || ! nix_direnv_version 3.0.5; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.5/direnvrc" "sha256-RuwIS+QKFj/T9M2TFXScjBsLR6V3A17YVoEW/Q6AZ1w="
fi
