#+TITLE: oxcl emacs config
#+AUTHOR: oxcl
#+DESCRIPTION: my personal emacs config
#+STARTUP: overview
#+PROPERTY: header-args :results silent
#+OPTIONS: toc:
* TABLE OF CONTENTS :toc:
* startup optimizations
most of theses optimizations are taken from doom emacs [[https://github.com/doomemacs/doomemacs/blob/master/lisp/doom.el][doom.el]]
#+begin_src elisp
    (unless init-file-debug
      (setq frame-inhibit-implied-size t
	    inhibit-startup-screen t
	    inhibit-startup-echo-area-message user-login-name
	    initial-major-mode 'fundamental-mode
	    initial-scratch-message nil
	    inhibit-redisplay t
	    inhibit-message t
	    read-process-output-max (* 1024 1024 3))
      (defun oxcl/reset-inhibited-vars-h ()
	(setq-default inhibit-redisplay nil
		      inhibit-message nil)
	(redraw-frame))
      (add-hook 'after-init-hook #'oxcl/reset-inhibited-vars-h)
      (define-advice startup--load-user-init-file (:after (&rest _) undo-inhibit-vars)
	(when init-file-had-error
	  (doom--reset-inhibited-vars-h)))
      (advice-add #'display-startup-echo_area-message :override #'ignore)
      (advice-add #'display-startup-screen :override #'ignore)
      (define-advice load-file (:override (file) silence)
	(load file nil 'nomessage))
      (define-advice startup--load-user-init-file (:before (&rest _) undo-silence)
	(advice-remove #'load-file #'load-file@silence))

      (advice-add #'tool-bar-setup :override #'ignore)
      (define-advice startup--load-user-init-file (:before (&rest _) defer-tool-bar-setup)
	(advice-remove #'tool-bar-setup #'ignore)
	(add-transient-hook! 'tool-bar-mode (tool-bar-setup))))
    #+end_src
    
* sane defaults
** unclutter working directory
*** relocate emacs user directory
because many packages including builtin ones use ~user-emacs-directory
#+begin_src elisp
  (setq real-user-emacs-directory user-emacs-directory)
  (setq user-emacs-directory oxcl/cache-dir)
  (setq server-auth-dir (expand-file-name "server" real-user-emacs-directory))
#+end_src

*** relocate backup files directory
#+begin_src emacs-lisp
  (setq backup-directory-alist `((".*" . ,(expand-file-name "emacs/backups" oxcl/cache-dir))))
#+end_src

*** relocate auto-save files directory
#+begin_src emacs-lisp
  (setq auto-save-file-name-transforms `((".*" ,(expand-file-name "emacs/save" oxcl/cache-dir) t)))
#+end_src

*** disable lockfiles
#+begin_src elisp
  (setq create-lockfiles nil)
#+end_src

** reduce verbosity
#+begin_src elisp
    ;; suppress compiler warnings
    (setq native-comp-async-report-warnings-errors init-file-debug
	  native-comp-warning-on-missing-source init-file-debug
	  ad-redefinition-action 'accept)
#+end_src

** enforce TLS
make sure internet communications are in TLS.this code is taken from [[https://github.com/doomemacs/doomemacs/blob/master/lisp/doom.el#L646][doomemacs]]
#+begin_src elisp
  (setq gnutls-verify-error noninteractive
	gnutls-algorithm-priority
	(when (boundp 'libgnutls-version)
	  (concat "SECURE128:+SECURE192:-VERS-ALL"
		  (if (and (not (memq system-type '(cygwin windows-nt ms-dos)))
			   (>= libgnutls-version 30605))
		      ":+VERS-TLS1.3")
		  ":+VERS-TLS1.2"))
	;; `gnutls-min-prime-bits' is set based on recommendations from
	;; https://www.keylength.com/en/4/
	gnutls-min-prime-bits 3072
	tls-checktrust gnutls-verify-error
	;; Emacs is built with gnutls.el by default, so `tls-program' won't
	;; typically be used, but in the odd case that it does, we ensure a more
	;; secure default for it (falling back to `openssl' if absolutely
	;; necessary). See https://redd.it/8sykl1 for details.
	tls-program '("openssl s_client -connect %h:%p -CAfile %t -nbio -no_ssl3 -no_tls1 -no_tls1_1 -ign_eof"
		      "gnutls-cli -p %p --dh-bits=3072 --ocsp --x509cafile=%t \
  --strict-tofu --priority='SECURE192:+SECURE128:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3' %h"
		      ;; compatibility fallbacks
		      "gnutls-cli -p %p %h"))
  
#+end_src

* package manager
** add local scripts to path
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "lisp" real-user-emacs-directory))
#+end_src

** straight.el
*** bootstrap
i use straight.el for it's locking mechanism
#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name
	  "straight/repos/straight.el/bootstrap.el"
	  (or (bound-and-true-p straight-base-dir)
	      user-emacs-directory)))
	(bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      ;; symlink the lockfiles from the .config directory into straight.el directory
      (let ((lockfile-path (expand-file-name "straight/versions" user-emacs-directory)))
	(make-directory lockfile-path t)
	(make-symbolic-link (expand-file-name "lockfile.el" real-user-emacs-directory)
			    (expand-file-name "default.el" lockfile-path)))
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

*** defaults
#+begin_src emacs-lisp
  ;; main user in hosting platforms to fetch the forked version of a package
  (setq straight-host-usernames
	'((github . "oxcl")))
  ;; how straight.el should know if a package repository was manually edited.
  (setq straight-check-for-modification '(find-when-checking watchexec))
#+end_src

*** automatic lockfile generation
automatically regenerate the lockfile when installing a new package or upgrading old ones
#+begin_src emacs-lisp
  (cl-defun oxcl/update-lockfile (&key commit repo-dir remote url branch depth)
    (unless commit
      (straight-freeze-versions)))
  (add-hook 'straight-vc-git-post-clone-hook 'oxcl/update-lockfile)
  (advice-add 'straight-pull-package
	      :after (lambda ()
		       (straight-freeze-versions)))
  (advice-add 'straight-pull-package-and-deps
	      :after (lambda ()
		       (straight-freeze-versions)))
  (advice-add 'straight-pull-all
	      :after (lambda ()
		       (straight-freeze_versions)))
#+end_src

** use-package
#+begin_src emacs-lisp
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

* ui
** sane defaults
#+begin_src emacs-lisp
    (setq ring-bell-function 'ignore ; disable visual or audible ring
	  overflow-newline-into-fringe nil)  ; stop cursor & chars from going in fringe zone
    (scroll-bar-mode -1)
    (tool-bar-mode -1) ; hide the tool bar (with the icons)
    (menu-bar-mode -1) ; hide the menu bar
    (tooltip-mode -1) ; hide tooltip popup window on mouse hover
    (blink-cursor-mode -1) ; disable cursor blink
    (set-fringe-mode '(0 . 10)) ; add small margin to the right of the editor
#+end_src
** font
#+begin_src emacs-lisp
  (set-frame-font "JetBrains Mono 8" nil t)
  (setq-default line-spacing 1) ; small padding between each line
#+end_src

** theme
customized modus-theme to match gruvbox-material
#+begin_src emacs-lisp
  (use-package modus-themes
    :config
    (setq modus-themes-bold-constructs t
	  modus-themes-italic-constructs t
	  modus-themes-org-blocks 'gray-background
	  modus-themes-prompts '(bold)
	  modus-themes-completions
	  (quote ((selection . (regular))))
	  modus-themes-headings
	  '((1 . (ultrabold 1.5))
	  (2 . (extrabold 1.3))
	  (3 . (bold 1.2))
	  (4 . (semibold 1.1))
	  (t . (bold 1.1))))
    (require 'gruvbox-material)
    (load-theme 'modus-vivendi :no-confirm)
    (require 'gruvbox-material-extras))
#+end_src

** line numbers column
#+begin_src emacs-lisp
  (setq-default display-line-numbers-width 4) ; how many digits for line numbers
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
#+end_src

** highlight current line
#+begin_src emacs-lisp
  (global-hl-line-mode)
  (add-hook 'comint-mode-hook (lambda () (setq-local global-hl-line-mode nil)))
  (add-hook 'org-mode-hook (lambda () (setq-local global-hl-line-mode nil))) ; org-mode has a lot of bugs with hl-line
#+end_src

** icons
all-the-icons fonts should be installed for this to work
#+begin_src elisp
(use-package all-the-icons
  :if (display-graphic-p))
#+end_src

* editor
** window management
*** scrolling
**** defaults
#+begin_src elisp
  (setq scroll-error-top-bottom t ; put the cursor at the top or bottom of the window if no more scrolls are possible
	scroll-conservatively 100 ; only scroll the minimum lines at a time when the cursor goes out the window
	scroll-margin 5) ; start scrolling the window when the distance between the cursor and the window boundaries are less than this number

#+end_src

**** scroll windows by half a page
scroll by half a page instead of a full bage whith PageDown/PageUp keys
also works with M-PageDown/M-PageUp (scroll-other-window/scroll-other-window-down)
#+begin_src elisp
  ;; make ScrollDown and ScrollUp Commands Scroll half a screen
  (defun oxcl/scroll-up-half ()
    (interactive)
    (scroll-up-command
     (floor
      (- (window-height)
	 next-screen-context-lines)
      2)))
  (defun oxcl/scroll-down-half ()
    (interactive)
    (scroll-down-command
     (floor
      (- (window-height)
	 next-screen-context-lines)
      2)))
  (defun oxcl/scroll-other-down-half()
    (interactive)
    (scroll-other-window-down
     (floor
      (- (window-height)
	 next-screen-context-lines)
      2)))
  (defun oxcl/scroll-other-up-half()
    (interactive)
    (scroll-other-window
     (floor
      (- (window-height)
	 next-screen-context-lines)
      2)))
  (global-set-key (kbd "<next>") 'oxcl/scroll-up-half)
  (global-set-key (kbd "<prior>") 'oxcl/scroll-down-half)
  (global-set-key (kbd "M-<next>") 'oxcl/scroll-other-up-half)
  (global-set-key (kbd "M-<prior>") 'oxcl/scroll-other-down-half)
#+end_src

*** navigation
**** ace
#+begin_src elisp
    (use-package ace-window
      :bind ("M-o" . 'ace-window)
      :config
      (setq aw-keys '(?a ?r ?s ?d ?g ?p ?d ?b ?v)))
#+end_src

** highlight current symbol
highlight the word/symbol under the cursor (with a small delay) and all its occurrences in the visible buffer
#+begin_src elisp
	    (use-package idle-highlight-mode
	      :hook ((prog-mode text-mode) . idle-highlight-mode)
	      :hook (org-mode . (lambda () (idle-highlight-mode -1)))
	      :custom
	      (idle-highlight-idle-time 0.25)
	      (idle-highlight-exceptions-face '(font-lock-comment-face)))
#+end_src

** jump to occurrence of symbol under the cursor
C-* jumps to the next occurrence the symbol that is under the cursor.
#+begin_src elisp
  ;; this function adds wrap functionality to smartscan.
  (defun oxcl/smartscan-wrap ()
    (interactive)
    (let ((symbol (smartscan-symbol-at-pt 'end))
	  (pos (point)))
      (when (smartscan-symbol-go-forward)
	  (beginning-of-buffer)
	  (smartscan-symbol-goto symbol 'forward)
	  (unless (bobp) (setq pos (point)))
	  (goto-char pos))))
    (use-package smartscan
      :config
      (global-smartscan-mode)
      (keymap-global-set "C-*" 'oxcl/smartscan-wrap))
#+end_src

** undo
*** linear undo
make undo behave more linearly like other applications.
keybindings are:
C-_   : normal undo
S-C-_ : normal redo
C-x u : emacs  undo
C-x U : emacs  redo
#+begin_src elisp
  (keymap-global-unset "C-/")
  (keymap-global-unset "C-?")
  (keymap-global-set "C-_" #'undo-only)
  (keymap-global-set "C--" #'undo-redo)
#+end_src

*** undo tree and branching

** persistent cursor position across sessions
#+begin_src elisp
  (save-place-mode 1)
  (setq save-place-forget-unreadable-files nil)
#+end_src

* spell checking
the builtin flyspell package will check each word under the cursor spelling against the specified backend.
#+begin_src elisp
  ;; ignore case sensitive spell checks
  (defun oxcl/jinx-lower-case-word-valid-p (start)
    "Return non-nil if word, that is assumed to be in lower case, at
     START is valid, or would be valid if capitalized or upcased."
    (let ((word (buffer-substring-no-properties start (point))))
      (or (member word jinx--session-words)
	  (cl-loop for dict in jinx--dicts thereis
		   (or
		    (jinx--mod-check dict (upcase word))
		    (jinx--mod-check dict (capitalize word))
		    (jinx--mod-check dict word))))))
  (defun oxcl/jinx-add-to-personal ()
    (interactive)
    (let ((word (current-word t t)))
      (jinx--save-personal t nil word)
      (jinx-mode -1)
      (jinx-mode 1)))
  (use-package jinx
    :hook ((text-mode prog-mode conf-mode org-mode) . jinx-mode)
    :custom
    (jinx-languages "en_US fa_IR")
    (jinx-camel-modes '(prog-mode conf-mode org-mode))
    (jinx-exclude-faces '((org-mode org-block-begin-line org-block-end-line)
			  (t font-lock-keyword-face font-lock-builtin-face)))
    :config
    (add-to-list 'jinx-exclude-regexps '(t "\\b[a-zA-Z]\\{2\\}\\b"))
    (set 'jinx--predicates
	 (cl-substitute
	  #'oxcl/jinx-lower-case-word-valid-p
	  #'jinx--word-valid-p
	  jinx--predicates))
    :bind
    ("C-$" . jinx-correct)
    ("C-@" . oxcl/jinx-add-to-personal))
#+end_src

* minibuffer
** history
*** persistent history across sessions
#+begin_src emacs-lisp
  (savehist-mode 1)
  (add-to-list 'savehist-additional-variables '(search-ring-regexp-search-ring file-name-history))
#+end_src

*** keybindings
#+begin_src elisp
  (defun oxcl/set-minibuffer-keybindings ()
    "Add custom keybindings for the  minibuffer."
    (local-set-key (kbd "M-<up>")   #'previous-history-element)
    (local-set-key (kbd "M-<down>") #'next-history-element))
  (add-hook 'minibuffer-setup-hook 'oxcl/set-minibuffer-keybindings)
#+end_src

** search and replace
*** make isearch better
**** sane defaults
#+begin_src emacs-lisp
  (setq-default case-fold-search nil ; make search case sensitive by default
		char-fold-symmetric t  ; accent character's match the regular character as well
		search-ring-max 64
		regexp-search-ring-max 64)
  ;; TODO: make sure char-fold-table includes farsi letters
#+end_src

**** frictionless search
#+begin_src emacs-lisp

  ;; while using incremental search when going from C-s to C-r or from C-r to C-s go to the
  ;; next/previous match immediately. instead of requiring two key presses
  (setq isearch-repeat-on-direction-change t)

  ;; make the backspace delete the search query immediately!
  ;; for going back to the previous match use C-r
  (define-key isearch-mode-map [remap isearch-delete-char] 'isearch-del-char)
  ;; clear the search string with C-S-<backspace> like other minibuffer prompts
  (defun oxcl/isearch-clear ()
    (interactive))
  (define-key isearch-mode-map (kbd "C-S-<backspace>") #'oxcl/isearch-clear)
  ;; automatically wrap around the buffer when no result is found
  (setq isearch-wrap-pause 'no)

  ;; exit out of search with a single C-g in all scenarios
  (defun oxcl/isearch-full-abort ()
    (interactive)
    (isearch-abort)
    (when isearch-mode (isearch-abort)))
  (define-key isearch-mode-map [remap isearch-abort] #'oxcl/isearch-full-abort)
#+end_src

**** isearch history
#+begin_src emacs-lisp
  (define-key isearch-mode-map (kbd "<M-up>") 'isearch-ring-retreat)
  (define-key isearch-mode-map (kbd "<M-down>") 'isearch-ring-advance)
#+end_src

;; when using C-s C-w to search for the word under the cursor grab the entire word
;; even if the cursor is in the middle of the word
(defun oxcl/isearch-yank-word-at-point ()
"Yank the whole word at point into the isearch buffer."
(interactive)
(save-excursion
(if (and (not isearch-forward)
isearch-other-end)
(goto-char isearch-other-end))
(skip-syntax-backward "w_")
(isearch-yank-string (buffer-substring-no-properties (point)
(progn (skip-syntax-forward "w_")
(point))))))

(define-key isearch-mode-map (kbd "C-w") 'oxcl/isearch-yank-word-at-point)

#+end_src

**** disable momentary messages
disable isearch annoying messages which appear after the search string and sometimes cause a delay
#+begin_src elisp
  (defun oxcl/isearch--momentary-message (orig-fun &rest args)
    (apply orig-fun `(,(car args) 0)))
  (advice-add 'isearch--momentary-message :around #'oxcl/isearch--momentary-message)
#+end_src

**** loose search
add two new keybindings for C-S-s and C-S-r which does a case insensetive incremental search with lax space enabled. and taking '-' and '_' as the same
so it's practically a less strict loose version of the normal isearch. it should also work in a isearch buffer as well to convert the current search to a loose one
#+begin_src elisp
  (defun oxcl/loose-search (&optional arg)
    (interactive)
    (if (bound-and-true-p oxcl/loose-search)
	(if (bound-and-true-p arg)
	    (isearch-repeat-backward)
	  (isearch-repeat-forward))
      (setq oxcl/loose-search t)
      (or (featurep 'char-fold) (require 'char-fold))
      (oxcl/enable-loose-color)
      (let ((case-fold-search t) ; case insensitive
	    (default-search-mode 'char-fold-to-regexp)
	    (search-upper-case nil)
	    (search-whitespace-regexp "[ .\t\n\\(\\)\\.,_-]+")) ; stops uppercase letters to change case sensitivity behavior
	(set-char-table-range char-fold-table ?_ "-")
	(set-char-table-range char-fold-table ?- "_")
	(if (bound-and-true-p arg) (isearch-backward) (isearch-forward))
	(set-char-table-range char-fold-table ?_ nil)
	(set-char-table-range char-fold-table ?- nil)
	(oxcl/disable-loose-color)
	(setq oxcl/loose-search nil))))
  (defun oxcl/loose-backward-search ()
    (interactive)
    (oxcl/loose-search t))
  (keymap-global-set "C-S-s" #'oxcl/loose-search)
  (keymap-global-set "C-S-r" #'oxcl/loose-backward-search)
  (defun oxcl/make-loose (&optional arg)
    (interactive)
    (unless (featurep 'char-fold) (require 'char-fold))
    (if (bound-and-true-p oxcl/loose-search)
	(if (bound-and-true-p arg)
	    (isearch-repeat-backward)
	  (isearch-repeat-forward))
      (setq oxcl/loose-search t)
      (isearch-toggle-case-fold)
      (isearch-toggle-char-fold)
      (oxcl/enable-loose-color))
      (add-hook 'isearch-mode-end-hook #'oxcl/disable-loose-color))
    (defun oxcl/make-loose-backward ()
      (interactive)
      (oxcl/make-loose t))
    (define-key isearch-mode-map (kbd "C-S-s") #'oxcl/make-loose)
    (define-key isearch-mode-map (kbd "C-S-r") #'oxcl/make-loose-backward)
#+end_src
**** search count (lazy highlight)
show total number of matches in the minibuffer
#+begin_src emacs-lisp
  (setq isearch-lazy-count t
	lazy-highlight-initial-delay 0)
#+end_src

**** more modern regex
replace emacs regex with a more modern functional regex
#+begin_src elisp
#+end_src
* which key
#+begin_src elisp
  (use-package which-key
    :config
    (which-key-mode)
    (setq which-key-idle-delay 6.0
	  which-key-idle-secondary-delay 0.05
	  which-key-show-early-on-C-h t))
#+end_src

* org mode
#+begin_src elisp
  (setq org-confirm-babel-evaluate nil)
  (define-key org-mode-map (kbd "C-.") 'org-edit-src-code)
  (define-key org-src-mode-map (kbd "C-.") 'org-edit-src-exit)
#+end_src

* programming
** tree-sitter
*** enable tree-sitter
replace builtin tree-sitter major modes with the old ones
#+begin_src elisp
  (setq major-mode-remap-alist '((ruby-mode . ruby-ts-mode)
				 (c++-mode . c++-ts-mode)
				 (c-or-c++-mode . c-or-c++-ts-mode)
				 (c-mode . c-ts-mode)
				 (java-mode . java-ts-mode)
				 (js-mode . js-ts-mode)
				 (csharp-mode . csharp-ts-mode)
				 (js-json-mode . json-ts-mode)
				 (css-mode . css-ts-mode)
				 (python-mode . python-ts-mode)
				 (conf-toml-mode . toml-ts-mode)
				 (sh-mode . bash-ts-mode)))
  (add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-ts-mode))
  (add-to-list 'auto-mode-alist '("go\\.mod\\'" . go-mod-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.yaml\\'" . yaml-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.go\\'" . go-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.cmake\\'" . cmake-ts-mode))
#+end_src

*** third-party ts-modes
since the builtin support for tree-sitter major modes is limited to few languages right now third-party packages are used as temporarily solution
**** clojure
#+begin_src elisp
  (use-package clojure-ts-mode
    :commands (clojure-ts-mode)
    :mode "\\.\\(clj\\|cljs\\|cljc\\)\\'")
#+end_src

**** kotlin
#+begin_src elisp
  (use-package kotlin-ts-mode
    :commands (kotlin-ts-mode)
    :mode "\\.kt\\'")
#+end_src

**** nix
#+begin_src elisp
  (use-package nix-ts-mode
    :commands (nix-ts-mode)
    :mode "\\.nix\\'")
#+end_src

**** lua
#+begin_src elisp
  (use-package lua-ts-mode
    :straight (:host sourcehut :repo "johnmuhl/lua-ts-mode")
    :mode "\\.lua\\'"
    :commands (lua-ts-mode))
#+end_src

** parenthesis and delimiters
*** rainbow delimiters
#+begin_src elisp
  (use-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src

*** highlight on hover
match the other pair of a delimiter on cursor hover
#+begin_src elisp
  (show-paren-mode)
  (setq show-paren-delay 0)
  (defun my-show-paren-any (orig-fun)
    (or (if (looking-at "\\s(") (funcall orig-fun))
	(if (looking-at "\\s)") (save-excursion (forward-char 1) (funcall orig-fun)))))
  (add-function :around show-paren-data-function #'my-show-paren-any)
#+end_src

*** jump to other pair
similar to vim % command
taken from [[https://www.emacswiki.org/emacs/NavigatingParentheses#h5o-2][emacs-wiki]]
#+begin_src elisp
  ;; since C-* is used also for smart-scan this function will fallback to oxcl/smartscan-wrap if the cursor
  ;; on a parenthesis
  (defun oxcl/goto-match-paren ()
    (interactive)
    (cond ((looking-at "\\s\(") (forward-list 1) (backward-char 1))
	  ((looking-at "\\s\)") (forward-char 1) (backward-list 1))
	  (t (oxcl/smartscan-wrap))))
  (keymap-global-set "C-*" #'oxcl/goto-match-paren)
#+end_src

*** auto close opening delimiters
#+begin_src elisp
  (electric-pair-mode)
  (setq electric-pair-skip-whitespace nil)
#+end_src

** indentation
*** hungry delete
#+begin_src elisp
  (defun oxcl/hungry-delete ()
    (interactive)
    (let (( current-line (buffer-substring-no-properties
			  (line-beginning-position)
			  (line-end-position))))
      (if (and (string-blank-p current-line) (not (string-empty-p current-line)))
	  (progn
	    (open-line 1)
	    (beginning-of-line)
	    (kill-line))
	(delete-backward-char 1))))
  (defun oxcl/add-hungry-delete-bindings ()
    (local-set-key (kbd "S-DEL") (key-binding (kbd "DEL")))
    (local-set-key (kbd "DEL") #'oxcl/hungry-delete))
  (add-hook 'prog-mode-hook #'oxcl/add-hungry-delete-bindings)
  (add-hook 'text-mode-hook #'oxcl/add-hungry-delete-bindings)
#+end_src

** git
*** magit
#+begin_src elisp
  (use-package magit)
#+end_src

** snippets and templates
*** yasnippet
#+begin_src elisp
  (use-package yasnippet
    :custom
    (yas-snippet-dirs `(,(expand-file-name "snippets" real-user-emacs-directory)))
    :config
    (yas-global-mode 1))
#+end_src
*** auto insert
automatically insert generic boilerplate via autoinsert and yasnippet when creating new files based on file extension
this code integrates yasnippet with the builtin yasnippet which is taken from  [[https://www.emacswiki.org/emacs/AutoInsertMod][emacs-wiki]]
#+begin_src elisp
	(defun oxcl/yas-insert ()
	  "Replace text in yasnippet templates."
	  (yas-expand-snippet (buffer-string) (point-min) (point-max)))

	(defun oxcl/setup-auto-insert ()
	  (unless (featurep 'autoinsert)
	    (require 'autoinsert)
	    (auto-insert-mode)
	    (setq auto-insert-query nil
		  auto-insert-directory (expand-file-name "auto-inserts/" real-user-emacs-directory)
		  auto-insert-alist '())
	    ;; automatically load auto-insert snippets from .config/emacs/auto-inserts folder.
	    ;; files which have only an underscore in the name will be applied to every file with that extension but only
	    ;; if a more specific template is not found.
	    (let ((auto-insert-files (cdr (cdr (directory-files (expand-file-name "auto-inserts" real-user-emacs-directory))))))
	      (dolist (item auto-insert-files)
		(let ((pattern-name (if (equal (file-name-base item) "_")
					(concat "\\." (file-name-extension item) "\\'")
				      (concat (file-name-base item) "\\." (file-name-extension item)))))
		  (add-to-list 'auto-insert-alist `(,pattern-name . [,item oxcl/yas-insert]) ))))))
  ;;	  auto-insert-alist '((("main\\.c\\'" . "main.c")   . ["main.c" oxcl/yas-insert])
  ;;			      (("\\.c\\'" . "c source") . ["_.c" oxcl/yas-insert]))))
	(oxcl/setup-auto-insert)
#+end_src

** completion
*** defaults
#+begin_src elisp
;;  (setq-default completion-styles '(basic))
#+end_src

*** company
**** defaults
#+begin_src elisp
    (use-package company
      :hook
      ((prog-mode org-mode conf-mode) . company-mode)
      :config
      (setq company-minimum-prefix-length 3
	    company-idle-delay (lambda () (if (company-in-string-or-comment) nil 0.2))
	    company-frontends '(company-pseudo-tooltip-frontend
				company-echo-metadata-frontend)
	    company-tooltip-align-annotations t
	    company-tooltip-annotation-padding 1
	    completion-at-point-functions '()
	    company-selection-wrap-around t
	    company-tooltip-width-grow-only t
	    company-tooltip-flip-when-above t
	    company-tooltip-minimum-width 60
	    company-backends '(company-files
			       (company-yasnippet company-dabbrev-code company-dabbrev))
	    company-tooltip-maximum-width 100
	    company-icon-margin 3
	    company-files-exclusions '(".git/" ".DS_STORE" "node_modules/")
  ;;	  company-transformers '(company-sort-by-backend-importance)
	    company-sort-prefer-same-case-prefix t))
#+end_src
comp
**** company-quick
vscode like documentation previewer on hover in the completion popup menu (tooltip)
#+begin_src elisp
  (use-package company-quickhelp
    :hook (company-mode . company-quickhelp-mode))
#+end_src
**** company-box
makes the company tooltip (popup menu) an actual floating frame instead of a child window of the current buffer
fixes display issues with org-mode
#+begin_src elisp
  (use-package company-box
    :after company
    :hook (company-mode . company-box-mode)
    :config
    (setq company-box-scrollbar 'right
	  company-box-doc-delay 0.2
	  company-box-doc-frame-parameters  '((internal-border-width . 1)
					      (left-fringe . 10)
					      (right-fringe . 10))
	  company-box-backends-colors '())
    (add-to-list 'company-box-frame-parameters '(scroll-bar-width . 7))
    (advice-add 'company-box-doc--make-buffer
		:filter-return (lambda (buffer)
				 (with-current-buffer buffer
				   (modus-themes-with-colors
				     (face-remap-add-relative 'fringe `(:background ,bg-dim :foreground ,bg-dim)))
				   buffer))))
#+end_src

*** prescient
sorts the completion candidates based on recent usage and frequency.
makes the auto completion smarter by putting more common and more recent completion candidates first
**** base

#+begin_src elisp
;;	(use-package prescient
;;	  :defer t
;;	  :config
;;	  (prescient-persist-mode))
#+end_src

**** prescient for company-mode
#+begin_src elisp
;;  (use-package company-prescient
;;    :requires prescient
;;    :after company
;;    :hook (company-mode . company-prescient-mode))
#+end_src

** LSP
*** lsp-mode
#+begin_src elisp
  (use-package lsp-mode
    :hook (
	   (lsp-mode . lsp-enable-which-key-integration)
	   (lsp-mode . (lambda ()
			 (make-local-variable 'company-backends)
			 (setq company-backends '(company-files
						  (company-yasnippet company-capf company-dabbrev-code))))))
  :commands lsp
  :config
  (setq lsp-log-io t
	lsp-auto-configure t
	lsp-enable-symbol-highlighting nil
	lsp-ui-doc-enable nil
	lsp-ui-doc-show-with-cursor nil
	lsp-ui-doc-show-with-mouse nil
	lsp-lens-enable nil
	lsp-headerline-breadcrumb-enable nil
	lsp-ui-sideline-enable nil
	lsp-ui-sideline-show-code-actions nil
	lsp-ui-sideline-show-hover nil
	lsp-modeline-code-actions-enable nil
	lsp-diagnostics-provider :none
	lsp-ui-sideline-show-diagnostics nil
	lsp-eldoc-enable_hover nil
	lsp-modeline-diagnostics-enable nil
	lsp-signature-auto-activate nil
	lsp-signature-render-documentation nil
	lsp-completion-enable t
	lsp-completion-show-detail t
	lsp-completion-show-kind t
	lsp-completion-sort-initial-results nil
	lsp-completion-filter-on-incomplete nil
	completion-at-point-functions '(lsp-completion-at-point)
	lsp-enable-suggest-server-download nil))
#+end_src

*** ccls
#+begin_src elisp
  (use-package ccls
    :hook ((c-mode c++-mode objc-mode cuda-mode c-ts-mode c++-ts-mode) . (lambda () (require 'ccls) (lsp)))
    :custom
    (ccls-sem-highlight-method 'overlay)
    (lsp-prefer-flymake nil)
    (ccls-initialization-options `(:cache      (:directory ,(expand-file-name "ccls-cache" (getenv "XDG_CACHE_HOME")))
				   :completion (:placeholder :json-false))))
#+end_src

** css
*** rainbow mode
colorize color codes like #ff0000 in the buffer.
it is automatically turned on for css,sass,scss and can be manually turned on with M-x rainbow-mode for other buffers
#+begin_src elisp
  (use-package rainbow-mode
    :hook (css-base-mode . rainbow-mode))
#+end_src

* dired
** sane defaults
#+begin_src elisp
  (setq delete-by-moving-to-trash t
	dired-listing-switches "-Ahl -v --group-directories-first"
	dired-dwim-target t
	dired-recursive-deletes t
	dired-kill-when-opening-new-dired-buffer t
	dired-create-destination-dirs t
	dired-auto-revert-buffer t)
  (add-hook 'dired-mode-hook #'dired-hide-details-mode)
#+end_src

** keybindings
#+begin_src elisp
  ;; toggle a dired buffer in other window for current directory with C-x C-d
  ;;  (keymap-global-set "C-x C-d" #'dired-jump-other-window)
  (add-hook 'dired-mode-hook (lambda () 
			       (local-set-key (kbd "C-x C-d") #'quit-window)
			       ;; home key moves to the first item in list instead of the dired header
			       (local-set-key (kbd "<C-home>") (lambda ()
								 (beginning-of-buffer)
								 (next-line)))
			       ;; end key moves to the last item in list instead of the empty line
			       (local-set-key (kbd "<C-end>") (lambda ()
								(end-of-buffer)
								(previous-line)))
			       ;; replace '% m' with '%' and '% g' with '$'
			       (local-set-key (kbd "%") #'dired-mark-files-regexp)
			       (local-set-key (kbd "$") #'dired-mark-files-containing-regexp)))
#+end_src

** icons
#+begin_src elisp
  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))
#+end_src

* Other

;; (global-set-key (kbd "C-x C-z") 'repeat) ; C-x C-z is easier than C-x z

;; disable wrapping when in programming mode
(defun oxcl/truncate-lines-in-buffers () (setq truncate-lines t))
(add-hook 'prog-mode-hook 'oxcl/truncate-lines-in-buffers)
(add-hook 'conf-mode-hook 'oxcl/truncate-lines-in-buffers)

;; this function is useful when you have the alias zshrc in the shell to quickly edit zsh
;; config files with emacs
(defun zshrc ()
  (progn
    (delete-window)
    (find-file (expand-file-name "rc.zsh" (getenv "ZDOTDIR")))
    (split-window-below)
    (other-window 1)
    (find-file (expand-file-name "env.zsh" (getenv "ZDOTDIR")))
    (split-window-horizontally)
    (find-file (expand-file-name "alias.zsh" (getenv "ZDOTDIR")))
    (other-window -1)))

;; load package.el
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("nongnu"  . "https://elpa.nongnu.org/nongnu/")
			 ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)



(use-package vterm)

(use-package easy-kill
  :config
;;  (global-set-key [remap kill-ring-save] 'easy-kill))

(use-package expand-region
  :config
;;  (global-set-key (kbd "C-=") 'er/expand-region))


(require 'move-lines)
(move-lines-binding)
