#!/usr/bin/env sh
# run different programs and daemons when graphical session (or ssh) starts. this file works for both wayland and x11 and ssh logins
# for x11 specific profile see ~/.config/x11/profile
# for wayland specific profile see ~/.config/wayland/profile
# for ssh specific profile see ~/.bash_profile

# loading necessary environment variables (environment variables are automatically loaded for terminals and shells that are called from your desktop environment or window manager)
source "${XDG_CONFIG_HOME:-$HOME/.config}/env"

# running simple python web server for my custom firefox/chrome user-scripts and home page
if command -v user-scripts &>/dev/null && [ -z "$USER_SCRIPT_SERVER_RUNNING" ]; then
  user-scripts &
fi
