name           = "Gruvbox Material Dark Soft"

bg             = "#202020"
fg             = "#d4be98"

black          = "#070808"
red            = "#ea6962"
green          = "#a9b665"
yellow         = "#d8a657"
blue           = "#7daea3"
magenta        = "#d3869b"
cyan           = "#89b482"
white          = "#e7d7bc"

bgDim          = "#070808"
bg0            = "#131414"
bg1            = "#2a2827"
bg2            = "#2e2c2b"
bg3            = "#32302f"
bg4            = "#3d3835"
bg5            = "#46403d"
bg6            = "#514945"
bg7            = "#5a524c"
bg8            = "#665c54"

fgDim          = "#c5b18d"
fgBright       = "#ddc7a1"

blackDim       = "#181919"
redDim         = "#b85651"
greenDim       = "#8f9a52"
yellowDim      = "#c18f41"
blueDim        = "#68948a"
magentaDim     = "#ab6c7d"
cyanDim        = "#72966c"
whiteDim       = "#ddc7a1"

# diy bright colors since gruvbox-material doesn't have bright colors (yet)
blackBright    = "#7c6f64"
redBright      = "#ef8f8a"
greenBright    = "#b6c17c"
yellowBright   = "#deb472"
blueBright     = "#94bcb3"
magentaBright  = "#dc9eaf"
cyanBright     = "#a5c69f"
whiteBright    = "#f1e9da"

orange         = "#e78a4e"
orangeDim      = "#bd6f3e"
