name           = "Gruvbox Material Dark Soft"

bg             = "#32302f"
fg             = "#d4be98"

black          = "#181919"
red            = "#ea6962"
green          = "#a9b665"
yellow         = "#d8a657"
blue           = "#7daea3"
magenta        = "#d3869b"
cyan           = "#89b482"
white          = "#ddc7a1"

bgDim          = "#181919"
bg0            = "#242424"
bg1            = "#3c3836"
bg2            = "#403c3a"
bg3            = "#45403d"
bg4            = "#504945"
bg5            = "#5a524c"
bg6            = "#665c54"
bg7            = "#7c6f64"
bg8            = "#928374"

fgDim          = "#c5b18d"
fgBright       = "#ddc7a1"

whiteDim       = "#c5b18d"
redDim         = "#b85651"
greenDim       = "#8f9a52"
yellowDim      = "#c18f41"
blueDim        = "#68948a"
magentaDim     = "#ab6c7d"
cyanDim        = "#72966c"
blackDim       = "#181919"

blackBright    = ""
redBright      = ""
greenBright    = ""
yellowBright   = ""
blueBright     = ""
magentaBright  = ""
cyanBright     = ""
whiteBright    = ""