#!/usr/bin/env sh
# make sure .xprofile is only sourced once due to a bug in nixos
if [ ! -z $_XPROFILE_SOURCED ]; then return; else export _XPROFILE_SOURCED=1; fi
# loading necessary environment variables for x11 ( environment variables are automatically loaded for terminals and shells that are called from your desktop environment or window manager)
source "${XDG_CONFIG:-$HOME/.config}/zsh/env.zsh"
source "${XDG_CONFIG:-$HOME/.config}/zsh/theme.zsh"

# load settings related to xterm, urxvt and programs that respect x11 settings
xrdb -DRED="$COLOR_RED" \
     -DGREEN="$COLOR_GREEN" \
     -DBLUE="$COLOR_BLUE" \
     -DPURPLE="$COLOR_PURPLE" \
     -DAQUA="$COLOR_AQUA" \
     -DYELLOW="$COLOR_YELLOW" \
     -DORANGE="$COLOR_ORANGE" \
     -DBG_COLOR="$COLOR_BG_1" \
     -DFG_COLOR="$COLOR_FG_1" \
     -DGREY_1="$COLOR_GREY_1" \
     -DGREY_2="$COLOR_GREY_2" \
     -DBG_DIM="$COLOR_BG_DIM" \
     "${XDG_CONFIG_HOME:-$HOME/.config}/x11/resources"

# run ssh-agent daemon
[[ -z "$SSH_AGENT_PID" ]] && eval "$(ssh-agent)"
# run gpg-agent daemon
command -v gpg-agent &> /dev/null && [[ -z "$GPG_AGENT_INFO" ]] && eval "$(gpg-agent --daemon)"

# run urxvt daemon
urxvtd -q -o &
