#!/usr/bin/env sh
# make sure .xprofile is only sourced once due to a bug in nixos
if [ ! -z $_XPROFILE_SOURCED ]; then return; else export _XPROFILE_SOURCED=1; fi
# loading necessary environment variables for x11 ( environment variables are automatically loaded for terminals and shells that are called from your desktop environment or window manager)
source "${XDG_CONFIG:-$HOME/.config}/env"
source "${XDG_CONFIG:-$HOME/.config}/themes/default"

# load settings related to xterm, urxvt, emacs and other programs that respect x11 settings
if [ -n "$MY_THEME_LOADED" ]; then
  xrdb $(eval echo "$(echo ${!MY_THEME_*} | xargs -n1 | xargs -I{} printf '-D{}=${} ' )") "${XDG_CONFIG_HOME:-$HOME/.config}/x11/resources"
fi

# set keyboard repeat delay and frequency
xset r rate 140 30
for keycode in {9..130}; do
    xset -r ${keycode};
done
xset r 113 # left arrow
xset r 114 # right arrow
xset r 111 # up arrow
xset r 116 # down arrow
xset r 117 # page down
xset r 112 # page up
xset r 23  # tab
xset r 22  # backspace
xset r 20  # underscore and minus
xset r 57  # n
xset r 26  # e
xset r 31  # i
xset r 58  # m
xset r 21  # plus and equal
xset r 13  # dollar sign
xset r 49  # tild sign
xset r 65  # space

# run ssh-agent daemon
[[ -z "$SSH_AGENT_PID" ]] && eval "$(ssh-agent)"

# run gpg-agent daemon
command -v gpg-agent &> /dev/null && [[ -z "$GPG_AGENT_INFO" ]] && eval "$(gpg-agent --daemon)"

# run urxvt daemon
if [[ "$TERMINAL" == "urxvt" ]] && command -v urxvtd &>/dev/null; then
  urxvtd -q -o &
fi
