#!/usr/bin/env sh
# make sure .xprofile is only sourced once due to a bug in nixos
if [ ! -z $_XPROFILE_SOURCED ]; then return; else export _XPROFILE_SOURCED=1; fi
# loading necessary environment variables for x11 ( environment variables are automatically loaded for terminals and shells that are called from your desktop environment or window manager)
source "${XDG_CONFIG:-$HOME/.config}/env"
source "${XDG_CONFIG:-$HOME/.config}/themes/default"

# load settings related to xterm, urxvt and programs that respect x11 settings
if [ -n "$MY_THEME_LOADED" ]; then
   xrdb $(eval echo "$(echo ${!MY_THEME_*} | xargs -n1 | xargs -I{} printf '-D{}=${} ' )") "${XDG_CONFIG_HOME:-$HOME/.config}/x11/resources"
fi

# run ssh-agent daemon
[[ -z "$SSH_AGENT_PID" ]] && eval "$(ssh-agent)"
# run gpg-agent daemon
command -v gpg-agent &> /dev/null && [[ -z "$GPG_AGENT_INFO" ]] && eval "$(gpg-agent --daemon)"

# run urxvt daemon
urxvtd -q -o &

