{ config,inputs,lib, pkgs, ... }:

{
  home.username = "user";
  home.homeDirectory = "/home/user";

  home.packages = with pkgs; [
    cmake
    python3
    git
    git-extras
    git-crypt # transparently encrypt certain files and folders in a git repository
    qmk
    rxvt-unicode-emoji # urxvt
    xclip
    lsd
    fzf
    jq
    direnv
    nix-direnv
    unzip
    ncdu
    noto-fonts-color-emoji
    (rofi.override { plugins = [ rofi-blocks ]; })
    bat
    pspg # tui table viewer for databases like postgress and .csv files
    w3m
    more
    most
    browsh
    zoxide
    tldr
    nuspell
    hunspellDicts.en-us-large
    hunspellDicts.en_US-large
    hunspellDicts.fa-ir
    hunspellDicts.fa_IR
    ccls
    ((emacsPackagesFor emacs29).emacsWithPackages (
      epkgs: with epkgs; [
	treesit-grammars.with-all-grammars
	jinx
      ]
    ))
    jetbrains-mono
    noto-fonts-emoji
    vazir-fonts
    vazir-code-font
    emacs-all-the-icons-fonts
    (nerdfonts.override { fonts = [ "JetBrainsMono" ]; })
    gnupg
    navi
    stow
    libfaketime
    poke
    nix-output-monitor
    websocat
    gh
    # archive and compression tools
    pigz
    pbzip2
    pixz
    lzip
    lz4
    rar
    zip
    cabextract
    p7zip
    asciinema
    asciinema-agg
    gifsicle
    fx
    neofetch
    lxd
    nodejs_21
    bun
    zsh-completions
    thefuck
    expect
    fq
    pup
    ttyper
    dconf
    overpass
    gruvbox-material-gtk
    sxiv
    hyperfine
    unstable.wezterm
    ffmpeg
    mpv
  ];

  programs.firefox = {
    enable = true;
    package = pkgs.firefox-bin;
    policies = (builtins.fromJSON (builtins.readFile ../../home/.config/firefox/policies.json)).policies;
  };

  services.gpg-agent = {
    enable = true;
    pinentryFlavor = "tty";
  };

  programs.chromium = {
    enable = true;
    dictionaries = with pkgs; [ hunspellDictsChromium.en_US ];
    commandLineArgs = [
      "--start-fullscreen" # if window manager is set up properly, chromium becomes borderless
      "--install-autogenerated-theme=37,36,35"
      # TODO: set gtk theme properly and remove this line
    ];
    extensions = [
      "cjpalhdlnbpafiamejdnhcphjbkeiagm" # ublock origin (backup file of all settings is stored in home/.config/chromium/ublock.txt)
      "eimadpbcbfnmbkopoojfekhnkhdbieeh" # dark reader
      "ldpochfccmkkmhdbclfhpagapcfdljkj" # decentraleyes
      "dgmanlpmmkibanfdgjocnabmcaclkmod" # just read
      "hokcepcfcicnhalinladgknhaljndhpc" # witchcraft
      "gfbliohnnapiefjpjlpjnehglfpaknnc" # surfingkeys
      "aleakchihdccplidncghkekgioiakgal" # h264fy
      "jpcmhcelnjdmblfmjabdeclccemkghjk" # view image
      "hdhinadidafjejdhmfkjgnolgimiaplp" # read aloud TTS
      "hkligngkgcpcolhcnkgccglchdafcnao" # web archives
      "lckanjgmijmafbedllaakclkaicjfmnk" # clear URLs
      "nkgllhigpcljnhoakjkgaieabnkmgdkb" # don't f*** with paste
      "bcjindcccaagfpapjjmafapmmgkkhgoa" # JSON formatter
      "mnjggcdmjocbbbhaepdhchncahnbgone" # Sponsorblock (settings backup file is stored in home/.config/chromium/sponsorblock.json)
      "icpgjfneehieebagbmdbhnlpiopdcmna" # new tab redirect
      "ocgpenflpmgnfapjedencafcfakcekcd" # redirector 
      "kaodcnpebhdbpaeeemkiobcokcnegdki" # github gloc
      "leicjbimaiecjfljbeikdailcmaadlml" # qr code
    ];
  };

  systemd.user.services.witchcraft-server = {
    Unit.Description = "local http server to host user-script files in ~/.config/chromium/user-scripts for witchcraft and new tab redirect chrome extensions to use";
    Install.WantedBy = [ "graphical-session.target" ];
    Service = {
      WorkingDirectory = "%h/.config/chromium/user-scripts";
      ExecStart = "${pkgs.python3}/bin/python3 -m http.server 5743 --bind 127.0.0.1";
    };
  };
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
    };
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  
  home.activation = {
    # automatically run my stow script to setup dotfiles in home directory after every home-manager/nixos rebuild
    myActivationAction = lib.hm.dag.entryAfter ["writeBoundary"] ''PATH="$PATH:${pkgs.stow}/bin" ${../../home/.local/bin/stowhome} '';
  };

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "23.05"; # Please read the comment before changing.
}
